services:
  pgvector:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: letmeask
    ports:
      - '5433:5432'
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
